# Generated by Django 2.2.5 on 2019-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dance.Step'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
