# Generated by Django 2.2.5 on 2019-10-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_auto_20191006_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_type',
            new_name='type',
        ),
    ]
