# Generated by Django 2.2.5 on 2019-10-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0003_auto_20191006_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dance.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='stepappearance',
            unique_together={('video', 'step', 'time')},
        ),
    ]
