# Generated by Django 2.2.5 on 2019-10-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0004_auto_20191009_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dance.Artist'),
        ),
    ]
