# Generated by Django 2.2.5 on 2019-10-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0006_auto_20191009_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.CharField(max_length=40),
        ),
    ]
