# Generated by Django 2.2.5 on 2019-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0007_auto_20191009_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='host',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Youtube'), (2, 'Instagram'), (3, 'Dailymotion')], default=0),
        ),
    ]
